### ISSUE TITLE
Issue creating image: missing release files

### ISSUE THREAD

**Issue by EricZinda** [LR-POR/delphin-docker#3]
On a mac, fresh install of docker:

Erics-MacBook-Pro:Delphin$ docker build -t logon image
Sending build context to Docker daemon  4.096kB
Step 1/15 : FROM ubuntu:18.10
18.10: Pulling from library/ubuntu
8a532469799e: Pull complete 
32f4dcec3531: Pull complete 
230f0701585e: Pull complete 
e01f70622967: Pull complete 
Digest: sha256:7d657275047118bb77b052c4c0ae43e8a289ca2879ebfa78a703c93aa8fd686c
Status: Downloaded newer image for ubuntu:18.10
 ---> 9dc19675e327
Step 2/15 : RUN dpkg --add-architecture i386
 ---> Running in a56ce690bada
Removing intermediate container a56ce690bada
 ---> a92ccd3b9031
Step 3/15 : RUN apt-get update -q
 ---> Running in e9a09139fa83
Ign:1 http://archive.ubuntu.com/ubuntu cosmic InRelease
Ign:2 http://security.ubuntu.com/ubuntu cosmic-security InRelease
Ign:3 http://archive.ubuntu.com/ubuntu cosmic-updates InRelease
Err:4 http://security.ubuntu.com/ubuntu cosmic-security Release
  404  Not Found [IP: 91.189.88.152 80]
Ign:5 http://archive.ubuntu.com/ubuntu cosmic-backports InRelease
Err:6 http://archive.ubuntu.com/ubuntu cosmic Release
  404  Not Found [IP: 91.189.88.152 80]
Err:7 http://archive.ubuntu.com/ubuntu cosmic-updates Release
  404  Not Found [IP: 91.189.88.152 80]
Err:8 http://archive.ubuntu.com/ubuntu cosmic-backports Release
  404  Not Found [IP: 91.189.88.152 80]
Reading package lists...
E: The repository 'http://security.ubuntu.com/ubuntu cosmic-security Release' does not have a Release file.
E: The repository 'http://archive.ubuntu.com/ubuntu cosmic Release' does not have a Release file.
E: The repository 'http://archive.ubuntu.com/ubuntu cosmic-updates Release' does not have a Release file.
E: The repository 'http://archive.ubuntu.com/ubuntu cosmic-backports Release' does not have a Release file.
The command '/bin/sh -c apt-get update -q' returned a non-zero code: 100

**Comment by arademaker** [comment]
Hi @EricZinda , hope this last commit solves this problem. Can you give a second try?

**Comment by arademaker** [comment]
ops! I will wait your feedback to close this issue.

**Comment by EricZinda** [comment]
Thanks so much @arademaker !  That fixed it
